### ISSUE TITLE
Problem in installing controller

### ISSUE THREAD

**Issue by vp7888** [zsavvas/MPTCP-aware-SDN#1]
when i try to build the controller i get the below error

init:

compile:
    [javac] Compiling 518 source files to /home/varun/MPTCP-aware-SDN/target/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /home/varun/MPTCP-aware-SDN/src/main/java/net/floodlightcontroller/topology/TopologyManager.java:90: error: duplicate class: net.floodlightcontroller.topology.TopologyManager
    [javac] public class TopologyManager implements IFloodlightModule, ITopologyService, IRoutingService, ILinkDiscoveryListener, IOFMessageListener {
    [javac]        ^
    [javac] /home/varun/MPTCP-aware-SDN/src/main/java/net/floodlightcontroller/TopologyManager.java:90: error: TopologyManager is not abstract and does not override abstract method getRoutes(DatapathId,DatapathId,boolean,int,boolean,String) in IRoutingService
    [javac] public class TopologyManager implements IFloodlightModule, ITopologyService, IRoutingService, ILinkDiscoveryListener, IOFMessageListener {
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors
    [javac] 1 warning

BUILD FAILED
/home/varun/MPTCP-aware-SDN/build.xml:143: Compile failed; see the compiler error output for details.

Total time: 4 seconds

**Comment by zsavvas** [comment]
Can you try again after pulling the latest changes?

Thanks

**Comment by vp7888** [comment]
Thanks..it works..i do have a some questions,1) did you use mininet to
simulate topology 2) was MTCP package installed in Mininet switches

regards
varun

**Comment by zsavvas** [comment]
1) Yes i used Mininet
2) MPTCP was installed on the host OS. In this way all the hosts that are created within the Mininet environment are MPTCP-enabled hosts

**Comment by vp7888** [comment]
got it..thanks..:)

On Wed, Feb 15, 2017 at 11:21 AM, Savvas Zannettou <notifications@github.com

**Comment by vp7888** [comment]
Hey savvas,
                  I am sorry to bug you again, but need your help. I was
trying to install Multilpath TCP in linux 4.4.0-57, installation shows
successful but "dmesg | grep MPTCP" gives me no output..can you please
suggest how did you install in your test bed.

regards
varun
